include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = MusicPlayerGNUstep

MusicPlayerGNUstep_HEADER_FILES = src/objc/AppDelegate.h src/objc/GuiController.h src/objc/NSOutlineViewTest.h
MusicPlayerGNUstep_OBJC_FILES =  src/objc/AppDelegate.m src/objc/GuiController.m src/objc/NSOutlineViewTest.m src/objc/main.m

include $(GNUSTEP_MAKEFILES)/application.make

